version: "2"

run:
  timeout: 30m

formatters:
  enable:
    - gofmt

linters:
  enable:
    - contextcheck
    - errorlint
    - makezero
    - misspell
    - nilerr
    - tagliatelle
    - unconvert
    - unparam
    - dupword
    - ineffassign
    - whitespace
  disable:
    - cyclop # Too many false positives for complex but necessary functions
    - wrapcheck # Too strict for this codebase
    - exhaustive # Too strict for switch statements
    - noctx # HTTP without context is fine for CLI tool
    - prealloc # Optimization suggestions, not errors
    - gocritic # Style suggestions, too noisy
    - errcheck # Too many false positives for defer Close() calls
    - staticcheck # Too strict style rules for this codebase
    - gosec # Too many false positives for CLI file processing tool
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
  whitespace:
    multi-func: true
  goimports:
    local-prefixes: adrianolaselva.github.io/csvql
  gosec:
    excludes:
      - G104  # Errors unhandled - acceptable in defer Close() calls
      - G115  # Integer overflow conversion - handled appropriately in this codebase
      - G201  # SQL string formatting - using parameterized queries where needed
      - G204  # Subprocess launched with variable - expected for CLI tool
      - G301  # Directory permissions - acceptable for temp directories
      - G304  # File inclusion via variable - expected for file processing tool
      - G306  # File permissions - acceptable for non-sensitive files
    config:
      global:
        nosec: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    # Exclude staticcheck ST1005 for error message capitalization
    - linters:
        - staticcheck
      text: "ST1005"